# Generated by Django 5.0 on 2023-12-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['departement'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(max_length=100)),
                ('drapeau', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom_pays'],
            },
        ),
        migrations.CreateModel(
            name='professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('civilite', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Communes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.departements')),
            ],
            options={
                'ordering': ['commune'],
            },
        ),
        migrations.CreateModel(
            name='format_cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_domicile', models.BooleanField(default=False)),
                ('webcam', models.BooleanField(default=False)),
                ('stage', models.BooleanField(default=False)),
                ('stage_webcam', models.BooleanField(default=False)),
                ('professeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
            options={
                'ordering': ['professeur', '-a_domicile', '-webcam'],
            },
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('actuellement', models.BooleanField(default=False)),
                ('commentaire', models.CharField(max_length=255)),
                ('principal', models.BooleanField(default=False)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
            options={
                'ordering': ['professeur', '-principal', '-debut'],
            },
        ),
        migrations.CreateModel(
            name='diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=100)),
                ('obtenu', models.DateField()),
                ('intitule', models.CharField(max_length=255)),
                ('priorite', models.BooleanField(default=False)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
            options={
                'ordering': ['-priorite', '-obtenu'],
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('nom_pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pays')),
            ],
            options={
                'ordering': ['region'],
            },
        ),
        migrations.AddField(
            model_name='departements',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.regions'),
        ),
    ]
