# Generated by Django 5.0 on 2023-12-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communes',
            new_name='Commune',
        ),
        migrations.RenameModel(
            old_name='Departements',
            new_name='Departement',
        ),
        migrations.RenameModel(
            old_name='format_cours',
            new_name='format_cour',
        ),
        migrations.RenameModel(
            old_name='Regions',
            new_name='Region',
        ),
        migrations.AlterField(
            model_name='professeur',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
    ]
