# Generated by Django 5.0 on 2024-04-16 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience_cathegorie',
            options={'ordering': ['nom_pays', 'exp_cathegorie']},
        ),
        migrations.RemoveField(
            model_name='experience_cathegorie',
            name='exp_ordre',
        ),
        migrations.AddField(
            model_name='experience_cathegorie',
            name='nom_pays',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.pays'),
            preserve_default=False,
        ),
    ]
