# Generated by Django 5.0 on 2023-12-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_communes_commune_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pro', models.CharField(max_length=100)),
                ('pass_prof', models.CharField(max_length=100)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
        ),
    ]
