# Generated by Django 5.0 on 2024-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_experience_cathegorie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience_cathegorie',
            options={'ordering': ['nom_pays']},
        ),
        migrations.AlterField(
            model_name='diplome_cathegorie',
            name='dip_cathegorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience_cathegorie',
            name='exp_cathegorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='experience_cathegorie',
            constraint=models.UniqueConstraint(fields=('nom_pays', 'exp_cathegorie'), name='unique_pays_experience'),
        ),
    ]
