# Generated by Django 5.0 on 2024-04-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_experience_cathegorie_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prof_email_telecharge',
        ),
    ]
