# Generated by Django 5.0 on 2023-12-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='diplome',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
    ]
