# Generated by Django 5.0 on 2023-12-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_diplome_diplome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='diplome',
            field=models.CharField(max_length=100),
        ),
    ]
