# Generated by Django 5.0 on 2024-04-24 08:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_prof_email_telecharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof_email_telecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_telechargement', models.DateField(default=datetime.date.today)),
                ('email_prof', models.CharField(blank=True, max_length=255, null=True)),
                ('sujet', models.CharField(blank=True, max_length=255, null=True)),
                ('text_email', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_telechargement'],
            },
        ),
    ]
