# Generated by Django 5.0 on 2023-12-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_diplome_diplome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='commune',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='departement',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nom_pays',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
