# Generated by Django 5.0 on 2024-04-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_prof_email_telecharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prof_email_telecharge',
            old_name='email_prof',
            new_name='email_telecharge',
        ),
    ]
