# Generated by Django 5.0 on 2024-04-24 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_email_prof_prof_email_telecharge_email_telecharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prof_email_telecharge',
            new_name='Email_telecharge',
        ),
    ]
