# Generated by Django 5.0 on 2023-12-30 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_commune_commune_alter_departement_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof_zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.commune')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
            options={
                'ordering': ['professeur'],
            },
        ),
    ]
