# Generated by Django 5.0 on 2023-12-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_prof_zone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prof_zone',
            constraint=models.UniqueConstraint(fields=('professeur', 'commune'), name='unique_prof_commune'),
        ),
    ]
