# Generated by Django 5.0 on 2024-04-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_prof_email_telecharge_email_telecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_telecharge',
            name='user_destinataire',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
