# Generated by Django 5.0 on 2023-12-31 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_prof_zone_unique_prof_commune'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere_cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_cathegorie', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau_cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niv_cathegorie', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100, unique=True)),
                ('mat_ordre', models.IntegerField(max_length=100, unique=True)),
                ('mat_cathegorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.matiere_cathegorie')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=100, unique=True)),
                ('niv_ordre', models.IntegerField(max_length=100, unique=True)),
                ('niv_cathegorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.niveau_cathegorie')),
            ],
        ),
        migrations.CreateModel(
            name='Prof_mat_niv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.niveau')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
            options={
                'ordering': ['professeur', 'matiere'],
            },
        ),
        migrations.AddConstraint(
            model_name='prof_mat_niv',
            constraint=models.UniqueConstraint(fields=('professeur', 'matiere', 'niveau'), name='unique_prof_mat_niv'),
        ),
    ]
