# Generated by Django 5.0 on 2024-04-25 11:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_email_telecharge_user_destinataire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suivi', models.CharField(choices=[('Ignorer', 'Ignorer'), ('Réception confirmée', 'Réception confirmée'), ('Répondre', 'Répondre')], max_length=25, null=True)),
                ('date_suivi', models.DateField(default=datetime.date.today)),
                ('email_suivi_id', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.email_telecharge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_suivi'],
            },
        ),
        migrations.AddConstraint(
            model_name='email_suivi',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='unique_user_email_suivi'),
        ),
    ]
