# Generated by Django 5.0 on 2023-12-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_matiere_cathegorie_niveau_cathegorie_matiere_niveau_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['mat_cathegorie', 'matiere']},
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='mat_ordre',
        ),
    ]
