# Generated by Django 5.0 on 2024-04-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_email_suivi_email_suivi_unique_user_email_suivi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email_suivi',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='email_suivi',
            name='unique_user_email_suivi',
        ),
    ]
