# Generated by Django 5.0 on 2023-12-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_matiere_options_remove_matiere_mat_ordre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['niveau']},
        ),
        migrations.AlterField(
            model_name='niveau',
            name='niv_ordre',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(fields=('niveau', 'niv_ordre'), name='unique_niv_ordre'),
        ),
    ]
