# Generated by Django 5.0 on 2024-04-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_email_suivi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_suivi',
            name='email_suivi_id',
        ),
    ]
