# Generated by Django 5.0 on 2024-04-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_email_suivi_email_suivi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_suivi',
            name='reponse_email_id',
            field=models.IntegerField(null=True),
        ),
    ]
