# Generated by Django 5.0 on 2023-12-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_niveau_options_alter_niveau_niv_ordre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere_cathegorie',
            options={'ordering': ['mat_cat_ordre']},
        ),
        migrations.AddField(
            model_name='matiere_cathegorie',
            name='mat_cat_ordre',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
