# Generated by Django 5.0 on 2024-04-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_email_suivi_reponse_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_detaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('matiere', models.CharField(blank=True, max_length=255, null=True)),
                ('niveau', models.CharField(blank=True, max_length=255, null=True)),
                ('format_cours', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.email_telecharge')),
            ],
        ),
    ]
