# Generated by Django 5.0 on 2023-12-31 10:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_matiere_cathegorie_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modif', models.DateField(default=datetime.date.today)),
                ('titre_fiche', models.CharField(max_length=255)),
                ('description_cours', models.TextField()),
                ('pedagogie', models.TextField()),
                ('video_youtube_url', models.CharField(max_length=255)),
                ('professeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
            options={
                'ordering': ['-date_modif'],
            },
        ),
        migrations.CreateModel(
            name='Prof_doc_telecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_telechargement', models.DateField(default=datetime.date.today)),
                ('doc_telecharge', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur')),
            ],
            options={
                'ordering': ['-date_telechargement'],
            },
        ),
    ]
