# Generated by Django 5.0 on 2023-12-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pro_fichier_prof_doc_telecharge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professeur',
            options={'ordering': ['nom']},
        ),
        migrations.AddConstraint(
            model_name='professeur',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom'), name='unique_nom_prenom'),
        ),
    ]
