# Generated by Django 5.0 on 2024-04-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_email_detaille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_detaille',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.email_telecharge'),
        ),
    ]
