# Generated by Django 5.0 on 2023-12-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_professeur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplome',
            options={'ordering': ['-principal', '-obtenu']},
        ),
        migrations.RenameField(
            model_name='diplome',
            old_name='priorite',
            new_name='principal',
        ),
    ]
