# Generated by Django 5.0 on 2023-12-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_diplome_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='civilite',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d/'),
        ),
    ]
