# Generated by Django 5.0 on 2023-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_professeur_civilite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compte',
            new_name='Compte_prof',
        ),
        migrations.AlterModelOptions(
            name='compte_prof',
            options={'ordering': ['user_pro']},
        ),
        migrations.AddConstraint(
            model_name='compte_prof',
            constraint=models.UniqueConstraint(fields=('user_pro', 'pass_prof'), name='unique_user_pass_prof'),
        ),
    ]
