# Generated by Django 5.0 on 2023-12-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_compte_compte_prof_alter_compte_prof_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte_prof',
            name='pass_prof',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='compte_prof',
            name='user_pro',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
