# Generated by Django 5.0 on 2023-12-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_compte_prof_pass_prof_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['departement']},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['region']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom_pays']},
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('departement', 'commune'), name='unique_departement_commune'),
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(fields=('region', 'departement'), name='unique_region_departement'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('nom_pays', 'region'), name='unique_pays_region'),
        ),
    ]
