# Generated by Django 5.0 on 2023-12-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_commune_options_alter_departement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='niveau',
            name='unique_niv_ordre',
        ),
        migrations.AddField(
            model_name='niveau_cathegorie',
            name='niv_ordre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matiere_cathegorie',
            name='mat_cat_ordre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='niv_ordre',
            field=models.IntegerField(),
        ),
    ]
