# Generated by Django 5.0 on 2024-01-01 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_niveau_options_remove_niveau_unique_niv_ordre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte_prof',
            name='professeur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.professeur'),
        ),
    ]
