# Generated by Django 5.0 on 2024-01-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_compte_prof_professeur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compte_prof',
            new_name='Compte',
        ),
    ]
