# Generated by Django 5.0 on 2024-01-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_compte_prof_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='professeur',
        ),
    ]
