# Generated by Django 5.0 on 2024-01-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_compte_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='compte',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.compte'),
            preserve_default=False,
        ),
    ]
