# Generated by Django 5.0 on 2024-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_professeur_compte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'ordering': ['user']},
        ),
        migrations.RemoveConstraint(
            model_name='compte',
            name='unique_user_pass_prof',
        ),
        migrations.RenameField(
            model_name='compte',
            old_name='pass_prof',
            new_name='mot_de_passe',
        ),
        migrations.RenameField(
            model_name='compte',
            old_name='user_pro',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='compte',
            constraint=models.UniqueConstraint(fields=('user', 'mot_de_passe'), name='unique_user_pass_prof'),
        ),
    ]
