# Generated by Django 5.0 on 2024-01-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_compte_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau_cathegorie',
            options={'ordering': ['niv_ordre']},
        ),
    ]
