# Generated by Django 5.0 on 2024-01-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_niveau_cathegorie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['niv_cathegorie', 'niv_ordre']},
        ),
    ]
