# Generated by Django 5.0 on 2024-01-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_niveau_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prof_mat_niv',
            options={},
        ),
    ]
