# Generated by Django 5.0 on 2024-01-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_prof_mat_niv_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prof_mat_niv',
            options={'ordering': ['professeur', '-principal', 'matiere', 'niveau']},
        ),
    ]
