# Generated by Django 5.0 on 2024-01-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_prof_mat_niv_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome_cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dip_cathegorie', models.CharField(max_length=100, unique=True)),
                ('dip_ordre', models.IntegerField()),
            ],
            options={
                'ordering': ['dip_ordre'],
            },
        ),
        migrations.AlterModelOptions(
            name='diplome',
            options={'ordering': ['professeur']},
        ),
        migrations.AddField(
            model_name='diplome',
            name='dip_cathegorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.diplome_cathegorie'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='diplome',
            constraint=models.UniqueConstraint(fields=('professeur', 'dip_cathegorie'), name='unique_prof_dip'),
        ),
    ]
