# Generated by Django 5.0 on 2024-01-03 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_diplome_cathegorie_alter_diplome_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_cathegorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_cathegorie', models.CharField(max_length=100, unique=True)),
                ('exp_ordre', models.IntegerField()),
            ],
            options={
                'ordering': ['exp_ordre'],
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['professeur']},
        ),
        migrations.AddField(
            model_name='experience',
            name='exp_cathegorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.experience_cathegorie'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('professeur', 'exp_cathegorie'), name='unique_prof_exp'),
        ),
    ]
