# Generated by Django 5.0 on 2024-01-03 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_experience_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_fichier',
            name='date_modif',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='pro_fichier',
            name='description_cours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pro_fichier',
            name='pedagogie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pro_fichier',
            name='video_youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
