# Generated by Django 5.0 on 2025-02-14 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_parent', models.CharField(max_length=255)),
                ('nom_parent', models.CharField(max_length=255)),
                ('civilite', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10, null=True)),
                ('telephone_parent', models.CharField(blank=True, max_length=15, null=True)),
                ('email_parent', models.CharField(blank=True, max_length=255, null=True)),
                ('code_carte', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_eleve', models.TextField(blank=True, null=True)),
                ('evaluation_eleve', models.PositiveSmallIntegerField(choices=[(1, 'Mauvais'), (2, 'Moyen'), (3, 'Bien'), (4, 'Très bien'), (5, 'Excellent')], default=3)),
                ('text_prof', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
                ('user_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoignages_eleve', to=settings.AUTH_USER_MODEL)),
                ('user_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoignages_prof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
