# Generated by Django 5.0 on 2024-04-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_alter_eleve_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
