# Generated by Django 5.0 on 2024-04-20 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_alter_eleve_adresse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_nom_parent', models.CharField(max_length=255)),
                ('nom_parent', models.CharField(max_length=255)),
                ('civilite', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('email_parent', models.CharField(blank=True, max_length=255, null=True)),
                ('code_carte', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
