# Generated by Django 5.0 on 2024-04-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='pre_nom_parent',
            new_name='prenom_parent',
        ),
    ]
