# Generated by Django 5.0 on 2024-04-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0005_rename_pre_nom_parent_parent_prenom_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='numero_telephone',
            new_name='telephone_parent',
        ),
    ]
